#!/bin/bash

# Ensure the submodules are up to date.
git submodule update

# Ensure the working tree is clean
if ! [[ -z "$(git status --porcelain)" ]]
then
	echo "ERR: Expected branch to be clean. Please stash your changes using 'git stash' before running this script."
	exit 1
fi

# Bump the version
existing_version=$(cat ./version)
build_number=$(( ${existing_version#*-} + 1 ))
protocol_version=${existing_version%%-*}

new_version="$protocol_version-$build_number"
echo $new_version > ./version

# Commit the change
git add version
git commit -S -m "chore(release): release $new_version"
# Create a tag
git tag "$new_version"

# Push the commit and tag
git push
git push -u origin "$new_version"
