# .github/workflows/release.yaml
# This file defines the workflows to release a new version of the BAP.

name: Release

# Run the actions when manually triggered or at 17:42 on every Tuesday.
on:
  workflow_dispatch:
  schedule:
    - cron: 42 17 * * 2

# The jobs to run.
jobs:
  # A workflow to create a release.
  create-release:
    name: Create
    # Run the job on a Linux machine.
    runs-on: ubuntu-latest
    steps:
      # `git-clone` the repository on the default branch.
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: true
      # Configure the user performing the release action.
      - name: Configure credentials
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Update the submodules
      - name: Update all sources
        run: ./scripts/sources
      # Run the release script.
      - name: Create a new release
        run: ./scripts/release
